### ISSUE TITLE
Agregar vista Tracker

### ISSUE THREAD

**Issue by CamilaPua** [esgaelramos/MyMoneyUP#9]
Definir ubicación de la vista, en core? en aplicación? (*parece mejor en aplicación, por si requiere más lógica específica, discutir*)
Incluye:
- [x] Discusión de 'Back' - 'Front' sobre necesidades la misma
- [x] Creación de url
- [x] Revisión de la vista

**Comment by esgaelramos** [comment]
Done like a first draft:)
BACK:
https://github.com/esgaelramos/MyMoneyUP/commit/8f6a6162eee4d722f1ab74ab466a97dc0d039849
https://github.com/esgaelramos/MyMoneyUP/commit/55080a59fa8c4640ff0382db8f82b8d155cf6967
FRONT:
https://github.com/esgaelramos/MyMoneyUP/commit/c3e35f328348f08ef81145bc187b95ee59d98cb5
https://github.com/esgaelramos/MyMoneyUP/commit/d345ea853512808df2b9eae09155dfb3493a12a3
https://github.com/esgaelramos/MyMoneyUP/commit/f385cde6634e704bd0fcd36e29f2bddf35f65ea2
